# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

environment:
  matrix:
    # node.js
    - nodejs_version: "0.12"
    # io.js
    - nodejs_version: "1"
    - nodejs_version: "2"
    - nodejs_version: "3"

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version && npm --version
  - cmd: npm test

build: off

matrix:
  fast_finish: true

cache:
  - '%AppData%\npm-cache -> package.json' # npm cache
