environment:
  matrix:
    # node.js
    - nodejs_version: "0.12"
    # io.js
    - nodejs_version: "1.0"
    - nodejs_version: "2.0"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

version: "{build}"

matrix:
  allow_failures:
    - nodejs_version: "12.0"
      platform: "x64"
    - nodejs_version: "1.0"
      platform: "x86"
    - nodejs_version: "1.0"
      platform: "x64"
    - nodejs_version: "2.0"
      platform: "x86"
    - nodejs_version: "2.0"
      platform: "x64"
